"use strict";
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/**import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});**/
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const dotenv_1 = __importDefault(require("dotenv"));
dotenv_1.default.config();
const config_1 = require("prisma/config");
exports.default = (0, config_1.defineConfig)({
    schema: "./prisma/schema.prisma",
    migrations: {
        path: "./prisma/migrations",
    },
    datasource: {
        url: process.env.DATABASE_URL,
    },
});
